"""Governance checks registry — single source of truth for all checks, categories, and remediation."""

from .checks import (
    check_metastore_connected,
    check_metastore_region,
    check_uc_compute,
    check_no_hive_data,
    check_hive_disabled,
    check_no_dbfs_mounts,
    check_scim_aim_provisioning,
    check_account_admin_group,
    check_metastore_admin_group,
    check_workspace_admin_group,
    check_catalog_admin_group,
    check_at_least_one_account_admin,
    check_account_admin_percentage,
    check_service_principals,
    check_production_access,
    check_group_ownership,
    check_abac_policy_adoption,
    check_governed_tags_applied,
    check_no_wildcard_grants,
    check_multiple_catalogs,
    check_catalog_binding,
    check_managed_tables_percentage,
    check_no_external_storage,
    check_external_location_root,
    check_storage_credentials,
    check_anomaly_detection_enabled,
    check_certification_tags_used,
    check_sensitive_data_classification,
    check_system_tables,
    check_predictive_optimization,
    check_data_quality,
    check_orphan_tables,
    check_table_column_comments,
    check_models_in_uc,
    check_mlflow_experiment_tracking,
)

# Each entry: (category, task_name, check_func, remediation_text)
GOVERNANCE_CHECKS = [
    # Platform Setup (Metastore + Compute + Migration)
    ("Platform Setup", "Connect a Metastore to your Workspace", check_metastore_connected,
     "Assign a Unity Catalog metastore to this workspace in Account Console > Workspaces. See: https://docs.databricks.com/data-governance/unity-catalog/get-started"),
    ("Platform Setup", "The workspace is in the same region as the metastore", check_metastore_region,
     "Deploy workspace and metastore in the same cloud region for performance and compliance. See: https://docs.databricks.com/data-governance/unity-catalog/"),
    ("Platform Setup", "Compute is UC activated with right access mode", check_uc_compute,
     "Set data_security_mode to USER_ISOLATION or SINGLE_USER on all clusters. Enable UC on SQL warehouses. See: https://docs.databricks.com/compute/configure"),
    ("Platform Setup", "No data in hive metastore", check_no_hive_data,
     "Migrate Hive metastore tables to Unity Catalog. See: https://docs.databricks.com/data-governance/unity-catalog/migrate"),
    ("Platform Setup", "Hive metastore is disabled", check_hive_disabled,
     "Disable the legacy Hive metastore in workspace settings after migrating all data. See: https://docs.databricks.com/data-governance/unity-catalog/migrate"),
    ("Platform Setup", "0 mount storage accounts to DBFS", check_no_dbfs_mounts,
     "Remove DBFS mounts and use Unity Catalog volumes or external locations instead. See: https://docs.databricks.com/volumes/"),

    # Identity & Access (Identity + Privileges + Fine-Grained Access Control)
    ("Identity & Access", "Use SCIM or AIM from an Identity Provider", check_scim_aim_provisioning,
     "Enable SCIM provisioning in Account Console > Settings > User provisioning to sync identities from your IdP (Azure AD, Okta, etc.). See: https://docs.databricks.com/admin/users-groups/scim/"),
    ("Identity & Access", "Account Admin role is assigned to a group", check_account_admin_group,
     "Create an admin group and assign the account_admin role to it instead of individual users. See: https://docs.databricks.com/admin/users-groups/"),
    ("Identity & Access", "Metastore Admin role is assigned to a group or to System User", check_metastore_admin_group,
     "Transfer metastore ownership to a group in Unity Catalog settings. See: https://docs.databricks.com/data-governance/unity-catalog/manage-privileges/admin-privileges"),
    ("Identity & Access", "Workspace Admin role is assigned to a group", check_workspace_admin_group,
     "Add an account-level group to the workspace admins group. See: https://docs.databricks.com/admin/users-groups/"),
    ("Identity & Access", "Catalog Admin role is assigned to a group", check_catalog_admin_group,
     "Transfer catalog ownership to groups using ALTER CATALOG ... SET OWNER TO. See: https://docs.databricks.com/data-governance/unity-catalog/manage-privileges/ownership"),
    ("Identity & Access", "At least 1 user is an account admin", check_at_least_one_account_admin,
     "Assign the account_admin role to at least one user or group in Account Console > User management. See: https://docs.databricks.com/admin/users-groups/"),
    ("Identity & Access", "Less than 5% of users are Account Admin", check_account_admin_percentage,
     "Reduce the number of account admins. Use groups for role-based access instead. See: https://docs.databricks.com/admin/users-groups/best-practices"),
    ("Identity & Access", "Production jobs use service principals", check_service_principals,
     "Configure jobs with run_as.service_principal_name for production workloads. See: https://docs.databricks.com/admin/users-groups/service-principals"),
    ("Identity & Access", "Modify access to production is limited", check_production_access,
     "Restrict MODIFY/WRITE privileges on production schemas to service principals only. See: https://docs.databricks.com/data-governance/unity-catalog/manage-privileges/"),
    ("Identity & Access", "70% of assets have groups as owners", check_group_ownership,
     "Transfer asset ownership to groups using ALTER ... SET OWNER TO. See: https://docs.databricks.com/data-governance/unity-catalog/manage-privileges/ownership"),
    ("Identity & Access", "ABAC policies actively used for centralized access control", check_abac_policy_adoption,
     "Configure ABAC policies at the catalog level. See: https://docs.databricks.com/data-governance/unity-catalog/abac/"),
    ("Identity & Access", "Governed tags applied to schemas and tables", check_governed_tags_applied,
     "Apply governed tags to classify data assets for ABAC, discoverability, and lifecycle management. See: https://docs.databricks.com/admin/governed-tags/"),
    ("Identity & Access", "No ALL PRIVILEGES wildcard grants on catalogs or schemas", check_no_wildcard_grants,
     "Replace ALL PRIVILEGES with specific grants (SELECT, USE CATALOG, USE SCHEMA). See: https://docs.databricks.com/data-governance/unity-catalog/manage-privileges/"),

    # Data Protection (Managed Storage + Data Quality Governance)
    ("Data Protection", "Create multiple Catalogs based on environment/BU/team", check_multiple_catalogs,
     "Create separate catalogs for dev/staging/prod or per business unit. See: https://docs.databricks.com/catalogs/"),
    ("Data Protection", "No Catalog is bound to all workspaces", check_catalog_binding,
     "Set catalog isolation mode to ISOLATED and bind to specific workspaces. See: https://docs.databricks.com/catalogs/binding"),
    ("Data Protection", "Use Managed tables and volumes > 70%", check_managed_tables_percentage,
     "Convert external tables to managed tables where possible for better governance. See: https://docs.databricks.com/tables/managed"),
    ("Data Protection", "No ADLS or S3 buckets outside UC", check_no_external_storage,
     "Migrate external storage to Unity Catalog managed storage or register as external locations. See: https://docs.databricks.com/connect/"),
    ("Data Protection", "No external volumes/tables at external location root", check_external_location_root,
     "Move external tables/volumes to subdirectories under external locations. See: https://docs.databricks.com/connect/"),
    ("Data Protection", "Independent storage credentials per external location", check_storage_credentials,
     "Create separate storage credentials for each external location for isolation. See: https://docs.databricks.com/connect/"),
    ("Data Protection", "Anomaly detection enabled for freshness and completeness", check_anomaly_detection_enabled,
     "Enable anomaly detection at the schema level for automatic freshness/completeness monitoring. See: https://docs.databricks.com/data-governance/unity-catalog/data-quality-monitoring/anomaly-detection/"),
    ("Data Protection", "Certification status tags used on tables", check_certification_tags_used,
     "Tag production tables as 'certified' and legacy tables as 'deprecated'. See: https://docs.databricks.com/data-governance/unity-catalog/certify-deprecate-data"),
    ("Data Protection", "Sensitive data classification scanning active", check_sensitive_data_classification,
     "Enable sensitive data classification to automatically detect PII and financial data. See: https://docs.databricks.com/admin/system-tables/data-classification"),

    # Data Quality & Observability (Audit & Lineage Coverage + Lineage & Discoverability)
    ("Data Quality & Observability", "All system tables activated (70%)", check_system_tables,
     "Enable more system table schemas in Unity Catalog for audit, billing, and lineage coverage. See: https://docs.databricks.com/admin/system-tables/"),
    ("Data Quality & Observability", "70% of managed tables have predictive optimization", check_predictive_optimization,
     "Enable predictive optimization on managed tables for automated maintenance. See: https://docs.databricks.com/optimizations/predictive-optimization"),
    ("Data Quality & Observability", "Data quality activated on 50% of tables", check_data_quality,
     "Enable data quality monitoring (anomaly detection) on more tables. See: https://docs.databricks.com/data-governance/unity-catalog/data-quality-monitoring/"),
    ("Data Quality & Observability", "Less than 10% orphan tables (no lineage in 90 days)", check_orphan_tables,
     "Review and deprecate/drop unused tables. Tag unused tables as deprecated. See: https://docs.databricks.com/data-governance/unity-catalog/certify-deprecate-data"),
    ("Data Quality & Observability", "Table and column comments coverage", check_table_column_comments,
     "Add descriptions to tables with COMMENT ON TABLE and to columns with ALTER TABLE ... ALTER COLUMN ... COMMENT. See: https://docs.databricks.com/sql/language-manual/sql-ref-syntax-ddl-comment"),

    # AI & Model Governance
    ("AI & Model Governance", "ML models registered in Unity Catalog", check_models_in_uc,
     "Migrate models from the workspace registry to Unity Catalog. See: https://docs.databricks.com/machine-learning/manage-model-lifecycle/"),
    ("AI & Model Governance", "MLflow experiment tracking active in UC", check_mlflow_experiment_tracking,
     "Configure MLflow experiments to use Unity Catalog for tracking. See: https://docs.databricks.com/mlflow3/genai"),
]
